### ISSUE TITLE
Feature Request: Add flag to minimize output to just show the branch name

### ISSUE THREAD

**Issue by allen-mckenzie** [daido1976/gh-default-branch#5]
I love this extension but the one thing I would get the most use out of would be to have it return just the name of the default branch so that it can be used in other scripts.

Example: gh default-branch show -name

Expected output: main

Currently: gh default-branch show

Output:  `Current default branch is "main"`

In order to make use of this output additional work must be done to isolate only the name of the branch so that it can be used in terminal scripts.

If this could be added it would make my day! 🥰

**Comment by daido1976** [comment]
@allen-mckenzie 
Thanks for the issue!
The `--name-only` option of the `show` subcommand is supported in `v0.6.0`.

```sh
# Show just the name of the default branch (e.g. main)
$ gh default-branch show --name-only

# There is also a shortened `-n` option
$ gh default-branch show -n
```

If you want to try it, please upgrade the extension.

```sh
$ gh extension upgrade daido1976/gh-default-branch
```
